PR #511: Improve validation messages (German and default) (#536)
* PR #511: Improve validation messages (German and default)

* fixed NoClassDefFoundError for ValidatorTypeCode due to incomplete ResourceBundle